import Head from "next/head"
import styles from "../styles/Home.module.css"

export const State = [
  {
    name: "Javascript list!",
    todo_tasks: [
      {
        id: 0,
        content: "javascript-todo",
        completed: false,
      },
      {
        id: 1,
        content: "react-todo",
        completed: true,
      },
    ],
  },
]

export const ToDoListItems = (props) => {
  const { list } = props

  return (
    <div>
      {list.map((v) => (
        <ToDoItem key={v.id} task={v}>
          {" "}
        </ToDoItem>
      ))}
    </div>
  )
}

export const ToDoItem = (props) => {
  const { task } = props

  return (
    <div className="flex">
      <input type="checkbox" defaultChecked={task.completed} />
      <h1>{task.content}</h1>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> ay.</h1>
      ayo?
      <ToDoListItems list={State[0].todo_tasks}></ToDoListItems>
    </div>
  )
}
